// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgtzjartmbylnooxtfjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhndHpqYXJ0bWJ5bG5vb3h0ZmptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5MzQyMTMsImV4cCI6MjA2MjUxMDIxM30.xmDeVH7M9NFqMl0-rYUpUQD7KG4vZpDkZyKbzobtqQU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);